import type { VoidV2Content } from "./void-v2-types";

export const VOID_V2_CONTENT = {
  hero: {
    code: "VOID",
    title: "寂静的边界",
    statement: ["你不是喜欢空", "你是在用空，把噪音筛出去"],
    traits: ["克制", "厚度", "仪式感"],
    styles: ["现代主义", "极简主义倾向", "批判性地域主义"],
    poster: "/images/void-v2/persona/void-hero-poster-v4.png",
    posterAlt: "VOID 寂静的边界人格海报，人物站在被光切开的混凝土空间中",
    background: "/images/void-v2/persona/void-hero-cross.webp",
    backgroundAlt: "混凝土厚墙被十字光切开",
    persona: "/images/void-v2/persona/void-persona.webp",
    personaAlt: "VOID 人格人物侧身望向光线",
  },
  digest: {
    label: "01 / 先说人话",
    title: "你的空间，不爱说废话",
    body: [
      "光得有方向，墙得有分寸，路最好别一眼走完",
      "你喜欢的是有理由的留白，每样东西都知道自己为什么待在这里",
    ],
    styleBridge: "翻译成建筑史，现代主义负责立骨架，极简主义倾向负责少说废话，批判性地域主义提醒它别忘了自己站在哪",
    caveat: "删得少不算本事，删完以后体验真的变了才算",
  },
  personality: {
    title: "你把安静当作空间的力量",
    passport: [
      { label: "第一反应", value: "删掉噪声" },
      { label: "核心需求", value: "让重要的东西被看见" },
      { label: "空间偏好", value: "厚度 / 边界 / 延迟抵达" },
    ],
    facets: [
      {
        index: "01",
        title: "别人看到的你",
        body: ["你不抢话，也不喜欢界面同时喊十件事", "你需要安静，才能把重要的东西看得很清楚", "安静帮你重新分配注意力"],
      },
      {
        index: "02",
        title: "你没有说出口的",
        body: ["你的感受并不少，甚至可能比别人更强", "只是习惯把它压缩成一道光、一段路或一次停顿"],
      },
      {
        index: "03",
        title: "信息过载时",
        body: ["清空桌面，退出群聊", "认真考虑把门改成一面墙", "先确认什么必须留下，再删除其余干扰"],
      },
    ],
    logicTitle: "空，是你管理注意力的方式",
    logic: ["它把噪声退到边界之外", "让光、脚步和时间重新显形"],
  },
  reactions: {
    title: "你挑风格时，其实在判断三件事",
    lead: "看似是三种偏好，其实都在做同一件事：管理注意力",
    counterpoint: "当光缝只负责好看、厚墙不改变进入、绕路只为了仪式感，它们就只是 VOID 的皮肤",
    items: [
      {
        id: "light",
        index: "01",
        title: "光",
        glyph: "光",
        role: "决定注意力最终落在哪里",
        headline: ["你会先看光从哪里进来", "再看它让什么变得重要"],
        body: ["光负责测量空间的厚度、方向和时间"],
        condition: "它必须同时改变朝向、停留或时间感",
        counterexample: "只在墙上留一道好看的发光缝",
        keywords: ["狭缝光", "明暗断层", "时间变化"],
        image: "/images/void-v2/reactions/light.webp",
        imageAlt: "狭缝光切开深色混凝土墙与地面",
        objectPosition: "center",
      },
      {
        id: "boundary",
        index: "02",
        title: "边界",
        glyph: "界",
        role: "决定什么应该被隔绝在外",
        headline: ["你需要内外有明确区别", "进入之前最好先停一下"],
        body: ["明确的边界不会让你窒息", "它反而让内外、明暗、公共与私密真正发生"],
        condition: "边界必须让内外、明暗或公共与私密真正发生",
        counterexample: "把厚墙当成沉重造型，却不改变进入方式",
        keywords: ["厚墙", "窄口", "门槛", "转折"],
        image: "/images/void-v2/reactions/boundary.webp",
        imageAlt: "厚重混凝土墙中的深门洞与门槛",
        objectPosition: "center 58%",
      },
      {
        id: "path",
        index: "03",
        title: "路径",
        glyph: "路",
        role: "决定你什么时候抵达核心",
        headline: ["你愿意晚一点抵达", "让转身与绕行成为空间的前奏"],
        body: ["动线决定身体何时停下、何时转身、何时第一次看见光"],
        condition: "绕行必须制造预期、转身或第一次看见光的时刻",
        counterexample: "为了显得有仪式感而增加无意义的路程",
        keywords: ["下沉", "折返", "延迟揭示"],
        image: "/images/void-v2/reactions/path.webp",
        imageAlt: "折返并下沉的混凝土路径最终通向一束光",
        objectPosition: "center",
      },
    ],
  },
  shadow: {
    headline: ["你对没有理由的热闹没兴趣", "留白也必须有分量"],
    desiredTitle: "你追求的",
    desired: ["有重量的安静", "可以触摸的光", "进入之前的停顿"],
    rejectedTitle: "你拒绝的",
    rejected: ["为了空而空", "没有层次的透明", "把克制当作装修风格"],
    darkTitle: "VOID 的危险",
    darkLead: "把克制误认成高级",
    darkBody: ["好的 VOID 靠每一次删减改变空间经验"],
  },
  styles: {
    title: "VOID 的三层结构",
    lead: ["当注意力管理被建筑化", "它需要骨架、纪律和地点"],
    image: "/images/void-v2/style/style-axonometric-v4.png",
    imageAlt: "结构骨架、切削体量与地域底板分层悬置的轴测模型",
    layers: [
      {
        id: "modernism",
        index: "01",
        name: "现代主义",
        role: "给 VOID 骨架",
        body: ["结构先于装饰", "材料、比例和建造逻辑必须保持诚实"],
        contribution: "结构先于装饰",
      },
      {
        id: "minimalism",
        index: "02",
        name: "极简主义倾向",
        role: "给 VOID 纪律",
        body: ["删到每一处都必须负责", "少意味着比例、接缝和光再也不能撒谎"],
        contribution: "每一处删减都必须负责",
      },
      {
        id: "regionalism",
        index: "03",
        name: "批判性地域主义",
        role: "让 VOID 保留地点",
        body: ["让抽象秩序重新经过场地", "气候、材料与身体经验阻止空间变成白盒子"],
        contribution: "抽象秩序必须重新经过场地",
      },
    ],
    closing: ["你对没有理由的热闹没兴趣", "留白也必须有分量"],
  },
  architect: {
    lead: ["真正对应你的", "是他如何控制光、边界与抵达"],
    interruption: "安藤和你同频，靠的是控制光与抵达",
    actionLead: "他反复用三个动作，把人的注意力重新集中",
    actions: ["切", "绕", "藏"],
    name: "安藤忠雄",
    originalName: "Tadao Ando",
    years: "1941—",
    descriptor: "用身体理解空间的自学者",
    storyTitle: "为什么要讲拳击和自学",
    story: [
      "拳击让他理解距离、节奏和身体移动",
      "自学经历让他习惯通过阅读、旅行和亲自走进建筑建立判断",
      "他习惯先控制人如何接近空间，再决定空间何时出现",
    ],
    image: "/images/void-v2/architect/tadao-ando.webp",
    imageAlt: "建筑师安藤忠雄黑白肖像",
    sectionLabel: "02 / 代表建筑师",
    sectionTitle: ["建筑界最会打拳的那位", "偏偏最会让空间安静"],
    summary: "没读过建筑学院，年轻时打过拳，后来靠阅读、旅行和一栋栋亲自走过去，把拳击里的距离、节奏和出手时机练进了墙、光和路径",
    detailTitle: "拳击早就练进了他的空间方法",
    detailBody: "拳击让安藤对距离、节奏和身体移动格外敏感，自学又让他习惯通过阅读、旅行和亲自进入建筑形成判断，他总把空间分段交付，先靠近，再转身、停下，最后让光出现",
    methodTitle: "他的强项，是控制空间的出场顺序",
    methodBody: "墙先挡住噪音，路径把抵达延迟，最后才轮到光出现，每个元素因此都有明确的任务",
    cta: "打开人物故事",
  },
  works: {
    title: "看懂 VOID 不用背理论，看三座建筑就够了",
    lead: "三栋建筑，三种把安静做出分量的方法",
    items: [
      {
        id: "cut",
        instinct: "光",
        action: "切",
        name: "光之教堂",
        originalName: "Church of the Light",
        year: "1989",
        location: "Ibaraki, Osaka",
        hook: ["一面混凝土墙被切开十字", "空间里最强的材料从墙变成了光"],
        cardHook: "他在墙上开了一刀，光把混凝土挤成了配角",
        detailTitle: "这一刀到底做对了什么",
        takeawayTitle: "可以带走的判断",
        cta: "看光怎么接管整个空间",
        observations: ["入口路径先绕过斜墙", "十字开口直接面对会众", "极少材料放大明暗变化"],
        story: [
          "人先绕过斜墙，进入昏暗室内，再被十字形光线迎面截住",
          "光把路线、朝向和停留组织在一起，成为空间的主构件",
        ],
        significance: "一道真实开口接管礼拜空间最核心的朝向，光从效果变成了秩序",
        keyFact: "斜墙迫使身体先偏离轴线，再转身面对十字光，光和路径在同一刻成立",
        takeaway: "一次有效的删减，会同时改变路线、朝向和停留，画面变干净只是附带结果",
        image: "/images/void-v2/works/church-of-light.webp",
        imageAlt: "光之教堂混凝土墙上的十字光口",
        objectPosition: "center",
        gallery: [
          { image: "/images/void-v2/works/details/church-light-detail-cross.webp", imageAlt: "光之教堂内部十字形开口的光照入混凝土空间" },
          { image: "/images/void-v2/works/details/church-light-exterior.webp", imageAlt: "光之教堂外部十字开口嵌入清水混凝土墙面" },
        ],
      },
      {
        id: "detour",
        instinct: "路径",
        action: "绕",
        name: "水御堂",
        originalName: "Water Temple / Honpukuji",
        year: "1991",
        location: "Awaji, Japan",
        hook: ["寺庙没有先出现屋顶", "人先看见一池荷花，再从水面中央向下消失"],
        cardHook: "寺庙藏在荷花池下面，想进去，先从水面消失",
        detailTitle: "他把屋顶变成了入口的障眼法",
        takeawayTitle: "可以带走的判断",
        cta: "看入口为什么藏在水下",
        observations: ["椭圆荷花池成为屋顶", "楼梯切开水面向下", "地下朱红空间与外部清水混凝土形成反差"],
        story: [
          "安藤提出把佛堂藏在莲花池下时，寺方最初几乎一致反对",
          "直到京都一位九十多岁的高僧认可了莲花作为佛教原点的解释",
          "人从平静水面向下进入朱红空间，传统没有被复制，却被重新经历",
        ],
        significance: "传统屋顶变成可以经过的水面，礼拜空间通过下行被身体一点点理解",
        keyFact: "荷花池同时是入口、屋顶和仪式界面，把日常地面与地下朱红佛堂分成两个世界",
        takeaway: "地域性可以藏在进入顺序和精神重心里，让传统通过身体继续发生",
        image: "/images/void-v2/works/water-temple.webp",
        imageAlt: "水御堂荷花池中央向下的混凝土楼梯",
        objectPosition: "center 58%",
        gallery: [
          { image: "/images/void-v2/works/details/water-temple-pond.webp", imageAlt: "水御堂的椭圆荷花池与水面边界" },
          { image: "/images/void-v2/works/details/water-temple-interior.webp", imageAlt: "水御堂内部被夕阳照亮的朱红礼拜空间" },
        ],
      },
      {
        id: "bury",
        instinct: "边界",
        action: "藏",
        name: "地中美术馆",
        originalName: "Chichu Art Museum",
        year: "2004",
        location: "Naoshima, Japan",
        hook: ["建筑大部分藏进地下", "把岛屿稳稳留在画面中央"],
        cardHook: "美术馆把自己埋进地下，只为了别抢整座岛的镜头",
        detailTitle: "藏起来，反而更有存在感",
        takeawayTitle: "可以带走的判断",
        cta: "看建筑怎么靠藏起来出场",
        observations: ["几何庭院切开地下体量", "自然光进入展厅", "路径不断收窄、转折再释放"],
        story: [
          "为了不让建筑压过直岛的地景，安藤把大部分空间埋进地下",
          "观众通过三角形与方形庭院辨认方向，在反复的明暗切换中慢慢校准眼睛",
        ],
        significance: "隐藏体量让岛屿继续占据主导，建筑只通过庭院、光和路径暴露自己的存在",
        keyFact: "三角形、方形与圆形空间共同承担地下辨向、采光和调节身体速度的任务",
        takeaway: "建筑主动让出画面中央，岛屿、光和时间自然成为主角",
        image: "/images/void-v2/works/chichu-courtyard.webp",
        imageAlt: "地中美术馆下沉混凝土庭院",
        objectPosition: "center",
        gallery: [
          { image: "/images/void-v2/works/details/chichu-entry.webp", imageAlt: "地中美术馆被树木与地形遮蔽的入口路径" },
          { image: "/images/void-v2/works/details/chichu-art-museum.webp", imageAlt: "地中美术馆的地下空间与自然光" },
        ],
      },
    ],
  },
  lineage: {
    title: ["安静这件事", "另外两位也很会"],
    lead: "康把它做成重量和秩序，卒姆托把它做成材料、温度和气氛",
    comparisonHeads: ["安藤忠雄", "路易斯·康", "彼得·卒姆托"],
    comparison: [
      { label: "光", values: ["切开空间", "建立秩序", "生成气氛"] },
      { label: "边界", values: ["厚墙与绕行", "重量与门槛", "材料与触感"] },
      { label: "路径", values: ["延迟揭示", "轴线与仪式", "身体与温度"] },
      { label: "方法", values: ["用切、绕、藏重新集中注意力", "用重量和秩序制造静默", "用材料和温度制造静默"] },
    ],
    items: [
      {
        name: "路易斯·康",
        originalName: "Louis I. Kahn",
        years: "1901—1974",
        method: "墙越厚，光越有分量",
        body: ["如果安藤是在墙上切开一道光", "康更像先让墙有了重量，再让光慢慢开口"],
        detailTitle: "他把安静做成秩序",
        detailBody: "康的空间很少急着讨好镜头，厚墙、拱顶和清晰的结构秩序让光显得更有分量，人在其中先感到被建筑接住，再慢慢意识到光从哪里来",
        relation: "他通过结构、光和门槛建立注意力秩序，这正是他和 VOID 同频的地方",
        featuredWork: "金贝尔艺术博物馆",
        workNote: "连续拱顶把自然光过滤后送进展厅，屋顶看似沉重，光却让它轻了起来",
        cta: "认识路易斯·康",
        keywords: ["重量", "秩序", "永恒"],
        image: "/images/void-v2/lineage/kimbell-art-museum-real.jpg",
        imageAlt: "路易斯·康设计的金贝尔艺术博物馆真实外景与连续拱顶",
        tone: "light",
      },
      {
        name: "彼得·卒姆托",
        originalName: "Peter Zumthor",
        years: "1943—",
        method: "建筑先别拍，进去待五分钟",
        body: ["温度、声音、触感和气味先进入空间", "建筑的图像随后才出现"],
        detailTitle: "他把气氛当成材料",
        detailBody: "卒姆托不急着把建筑变成一个容易传播的轮廓，他更在意材料摸起来怎样、脚步听起来多远、温度如何改变停留，以及光落在表面时空间有没有开始呼吸",
        relation: "他和 VOID 同频的地方，是让安静先成为身体经验，再成为可以被拍下来的画面",
        featuredWork: "瓦尔斯温泉",
        workNote: "片麻岩、暗光、回声和水温共同组织空间，建筑成为一整套身体感受",
        cta: "认识彼得·卒姆托",
        keywords: ["材料", "身体", "气氛"],
        image: "/images/void-v2/lineage/therme-vals-real.jpg",
        imageAlt: "彼得·卒姆托设计的瓦尔斯温泉真实外景与片麻岩立面",
        tone: "dark",
      },
    ],
    furtherTitle: "继续看，这种判断还会怎样发生",
    further: [
      {
        name: "沃思堡现代艺术博物馆",
        originalName: "Modern Art Museum of Fort Worth",
        years: "1997—2002",
        hook: "五片平顶展馆落在水池边，巨大的 Y 形混凝土柱让屋顶同时沉重又漂浮",
        keywords: ["水面", "Y 形柱", "水平地景"],
        image: "/images/void-v2/further/modern-fort-worth.jpg",
        imageAlt: "沃思堡现代艺术博物馆的水面、平顶展馆与 Y 形混凝土柱",
      },
      {
        name: "21_21 DESIGN SIGHT",
        originalName: "21_21 DESIGN SIGHT",
        years: "2004—2007",
        hook: "一片折叠钢屋顶低低贴住草坡，大部分展览空间安静地藏到地下",
        keywords: ["折板屋顶", "贴地开口", "地下空间"],
        image: "/images/void-v2/further/2121-design-sight.jpg",
        imageAlt: "21_21 DESIGN SIGHT 的折叠钢屋顶贴近草坡",
      },
    ],
  },
  ending: {
    judgment: ["空间一安静，重要的东西就有了主场", "让杂音退到边界之外", "光、材料和人的动作自然被看见"],
    primaryAction: "保存 VOID 人格封面",
    secondaryAction: "分享 VOID",
    socialPrompt: "发给那个总想往你家再塞点东西的人",
    previewCaption: "分享卡已经生成，长按图片或直接分享给朋友",
    generateError: "分享卡生成失败，请稍后重试",
    saveNotice: "若浏览器没有直接下载，请长按下方图片保存",
    shareSuccess: "分享面板已打开",
    retest: "重新测试",
    sources: "查看测试方法与图片来源",
  },
} as const satisfies VoidV2Content;
