import type { Architect } from "./schema";

export const ARCHITECTS: readonly Architect[] = [
  {
    id: "ARCH-MIES",
    name: "密斯·凡·德·罗",
    originalName: "Ludwig Mies van der Rohe",
    lifespan: "1886—1969",
    region: "德国出生，后在美国工作",
    school: "现代主义 / 国际主义",
    summary: "他把结构、比例与材料压缩成极少的动作：柱子退开，墙体游走，石材与玻璃承担全部戏剧",
    storyTitle: "被拆掉的经典，以及不能被删掉的合作者",
    story: "1929 年巴塞罗那德国馆在博览会结束后被拆除，却在建筑史中持续放大，最终于 1986 年在原址重建。展馆与 Barcelona Chair 的设计都应同时看到 Lilly Reich 的合作贡献；这个结果不把现代主义重新讲成单一男性天才神话",
    creditNote: "巴塞罗那馆与家具须注明 Lilly Reich；西格拉姆大厦注明 Philip Johnson 等合作。",
    portrait: {
      src: "/images/architects-v2/mies.webp",
      alt: "密斯·凡·德·罗风格化肖像：白发、深色西装，坐在巴塞罗那馆抽象背景前",
      source: { label: "Wikimedia Commons · Ludwig Mies van der Rohe", url: "https://commons.wikimedia.org/wiki/File:Ludwig_Mies_van_der_Rohe_in_Arts_%26_Architecture,_June_1960_issue.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Fundació Mies van der Rohe · The Pavilion", url: "https://miesbcn.com/the-pavilion/" },
      { label: "MoMA · Ludwig Mies van der Rohe", url: "https://www.moma.org/artists/7166" },
    ],
  },
  {
    id: "ARCH-WRIGHT",
    name: "弗兰克·劳埃德·赖特",
    originalName: "Frank Lloyd Wright",
    lifespan: "1867—1959",
    region: "美国",
    school: "有机建筑 / 草原学派",
    summary: "他把地形、材料、家具和人的生活组织成一个整体，让建筑真正进入风景",
    storyTitle: "他没有把瀑布放在窗外",
    story: "流水别墅靠一个激进决定被记住：住宅的混凝土平台直接从岩石与水流上方伸出。住户持续听见瀑布、走在水流上方，风景从观看对象变成居住条件",
    creditNote: "作品说明应区分 Wright 个人设计、Taliesin Fellowship 与后续保存团队。",
    portrait: {
      src: "/images/architects-v2/wright.webp",
      alt: "弗兰克·劳埃德·赖特风格化肖像：白发、深色西装，一手托住太阳穴，背后是抽象流水别墅",
      source: { label: "Frank Lloyd Wright Foundation", url: "https://franklloydwright.org/frank-lloyd-wright/", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Frank Lloyd Wright Foundation · Fallingwater", url: "https://franklloydwright.org/site/fallingwater/" },
      { label: "Frank Lloyd Wright Foundation · Robie House", url: "https://franklloydwright.org/site/robie-house/" },
    ],
  },
  {
    id: "ARCH-CORBU",
    name: "勒·柯布西耶",
    originalName: "Le Corbusier / Charles-Édouard Jeanneret-Gris",
    lifespan: "1887—1965",
    region: "瑞士出生，主要在法国工作",
    school: "现代主义 / 粗野主义源流",
    summary: "他用住宅、模数与城市系统同时思考个体和集体；作品既有强烈秩序，也留下粗粝材料与巨大争议",
    storyTitle: "一栋楼里塞进一座城市",
    story: "马赛公寓把复式住宅、内部商业街、托儿与屋顶设施叠在同一体量中，被构想为一座垂直城市。André Wogenscky 领导的工作室与 ATBAT 团队共同参与了实现",
    creditNote: "马赛公寓注明 Atelier Le Corbusier、André Wogenscky 与 ATBAT；昌迪加尔注明项目团队与当地合作者。",
    portrait: {
      src: "/images/architects-v2/le-corbusier.webp",
      alt: "勒·柯布西耶风格化肖像：光头、黑色圆框眼镜与深色领结，背后是抽象马赛公寓",
      source: { label: "Fondation Le Corbusier · 1939–1946", url: "https://www.fondationlecorbusier.fr/en/biography/1939-1946/", credit: "Portrait © Bodé / Fondation Le Corbusier", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Fondation Le Corbusier · Unité d'Habitation", url: "https://www.fondationlecorbusier.fr/en/work-architecture/achievements-unite-dhabitation-marseille-france-1945-1952/" },
      { label: "Fondation Le Corbusier · La Tourette", url: "https://www.fondationlecorbusier.fr/oeuvre-architecture/realisations-couvent-sainte-marie-de-la-tourette-eveux-sur-larbresle-france-1953-1960/" },
    ],
  },
  {
    id: "ARCH-ANDO",
    name: "安藤忠雄",
    originalName: "Tadao Ando",
    lifespan: "1941—",
    region: "日本",
    school: "诗意极简 / 清水混凝土",
    summary: "他的建筑常用极少材料和绕行路径，把光、风、水与身体感受放大到近乎宗教性的程度",
    storyTitle: "先绕路，再看到光",
    story: "安藤的空间经常拒绝最短路线：人要绕过墙、向下走或穿过水面，才抵达核心。光之教堂把十字形开口切进混凝土墙，最简单的几何因此成为最强烈的感受",
    portrait: {
      src: "/images/architects-v2/ando.webp",
      alt: "安藤忠雄风格化肖像：黑色直发、深色外套与高白领，背后是光之教堂的十字形开口",
      source: { label: "Wikimedia Commons · Tadao Ando", url: "https://commons.wikimedia.org/wiki/File:Tadao_Ando_2004_(4x5_cropped).jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "The Pritzker Architecture Prize · Tadao Ando", url: "https://www.pritzkerprize.com/laureates/1995" },
      { label: "Benesse Art Site Naoshima · Chichu Art Museum", url: "https://benesse-artsite.jp/en/art/chichu.html" },
    ],
  },
  {
    id: "ARCH-FOSTER",
    name: "诺曼·福斯特",
    originalName: "Norman Foster / Foster + Partners",
    lifespan: "1935—",
    region: "英国及全球",
    school: "高技派",
    summary: "他把结构、环境系统、交通与公共空间当成同一台大型机器来设计，同时不断追求更轻、更透明的城市基础设施",
    storyTitle: "系统理性也要问风水",
    story: "香港汇丰总行几乎所有部件都为项目专门设计并在外地制造后运到香港装配。项目还纳入了风水顾问，技术因此进入具体城市文化，系统思维也多了一层现场判断",
    creditNote: "所有作品使用 Foster + Partners 团队署名，不简化成 Foster 独立完成。",
    portrait: {
      src: "/images/architects-v2/foster.webp",
      alt: "诺曼·福斯特风格化肖像：银灰短发、浅蓝衬衫，双臂交叠站在汇丰总行抽象桁架前",
      source: { label: "The Pritzker Architecture Prize · Norman Foster", url: "https://www.pritzkerprize.com/laureates/1999", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Foster + Partners · Hongkong and Shanghai Bank Headquarters", url: "https://www.fosterandpartners.com/projects/hongkong-and-shanghai-bank-headquarters/" },
      { label: "HSBC · Back to the future", url: "https://www.hsbc.com/news-and-views/news/hsbc-news-archive/back-to-the-future" },
    ],
  },
  {
    id: "ARCH-ZAHA",
    name: "扎哈·哈迪德",
    originalName: "Zaha Hadid / Zaha Hadid Architects",
    lifespan: "1950—2016",
    region: "伊拉克出生，英国及全球",
    school: "解构主义 / 新未来主义",
    summary: "她把绘画中的碎裂透视、速度与连续地形推进到真实建造，让空间保持正在发生的速度感",
    storyTitle: "纸上的高速城市终于落地",
    story: "她早期许多激进方案主要通过竞赛图与绘画被认识，长期被称作难以建成的“纸上建筑师”。随着数字设计、工程与制造能力变化，那些倾斜、流动与连续的空间才逐渐成为城市中的真实建筑",
    creditNote: "2016 年后的作品与大型项目均使用 Zaha Hadid Architects 团队署名。",
    portrait: {
      src: "/images/architects-v2/zaha.webp",
      alt: "扎哈·哈迪德风格化肖像：深色长发与黑色外套，背后是海达尔·阿利耶夫中心的抽象曲线",
      source: { label: "Wikimedia Commons · Zaha Hadid", url: "https://commons.wikimedia.org/wiki/File:Zaha_Hadid_in_Heydar_Aliyev_Cultural_center_in_Baku_nov_2013.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Zaha Hadid Architects · Architecture", url: "https://www.zaha-hadid.com/architecture/" },
      { label: "The Pritzker Architecture Prize · Zaha Hadid", url: "https://www.pritzkerprize.com/laureates/2004" },
    ],
  },
  {
    id: "ARCH-GAUDI",
    name: "安东尼·高迪",
    originalName: "Antoni Gaudí",
    lifespan: "1852—1926",
    region: "加泰罗尼亚",
    school: "加泰罗尼亚现代主义 / 新艺术",
    summary: "他把结构实验、自然几何、宗教叙事和工匠技术揉成总体艺术，装饰直接从建造逻辑里长出",
    storyTitle: "失败住宅区变成了城市乐园",
    story: "Park Güell 原本是受英国花园城市启发的高端住宅开发，但销售困难，最终只建成两栋住宅。失败的地产计划后来变成公共公园，曲线长椅、碎瓷拼贴与基础设施反而获得了更长的城市生命",
    creditNote: "圣家堂持续由多代建筑师、工匠和工程团队推进，不能写成高迪独自完成。",
    portrait: {
      src: "/images/architects-v2/gaudi.webp",
      alt: "安东尼·高迪风格化肖像：侧分深发、浓密胡须与深色历史西装，背后是巴特罗之家抽象立面",
      source: { label: "Wikimedia Commons · Antoni Gaudí", url: "https://commons.wikimedia.org/wiki/File:Antoni_Gaudi_1878.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Casa Batlló · Gaudí works", url: "https://www.casabatllo.es/en/antoni-gaudi/works/" },
      { label: "Casa Batlló · Park Güell", url: "https://www.casabatllo.es/en/antoni-gaudi/park-guell/" },
    ],
  },
  {
    id: "ARCH-WANG-LU",
    name: "王澍 × 陆文宇",
    originalName: "Wang Shu × Lu Wenyu / Amateur Architecture Studio",
    lifespan: "1963— / 1967—",
    region: "中国",
    school: "批判地域主义 / 材料再生",
    summary: "他们用回收砖瓦、地方工法和当代空间重新连接快速城市化中被切断的材料记忆",
    storyTitle: "为什么工作室偏要叫“业余”",
    story: "“业余建筑工作室”这个名字主动与只剩生产效率的职业系统保持距离。宁波历史博物馆的旧砖瓦来自周边拆迁地区，材料以新的墙体重新出现，也把消失村落的一部分时间带回城市",
    creditNote: "人物与项目内容必须同时呈现陆文宇、王澍、业余建筑工作室和建造团队，避免单一获奖者叙事。",
    portrait: {
      src: "/images/architects-v2/wang-lu.webp",
      alt: "王澍与陆文宇的双人风格化肖像：两人等距并肩站立，背后是宁波历史博物馆的抽象墙面",
      source: { label: "Wallpaper* · Wang Shu and Lu Wenyu", url: "https://www.wallpaper.com/architecture/wang-shu-and-lu-wenyu-curators-2027-venice-architecture-biennale", credit: "La Biennale di Venezia / ASAC / Matteo Losurdo", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Pritzker Prize · Wang Shu essay", url: "https://www.pritzkerprize.com/sites/default/files/file_fields/field_files_inline/2013_essay.pdf" },
      { label: "Pritzker Prize · The Infinite Spontaneity of Tradition", url: "https://www.pritzkerprize.com/sites/default/files/inline-files/2012_Essay_0.pdf" },
    ],
  },
  {
    id: "ARCH-FREI-OTTO",
    name: "弗莱·奥托",
    originalName: "Frei Otto",
    lifespan: "1925—2015",
    region: "德国",
    school: "轻量结构 / 形态生成",
    summary: "他用悬链、肥皂膜和网壳模型让真实受力先找到形状，再由建筑师与工程师共同把轻量空间放大",
    storyTitle: "肥皂泡替工程师画的草图",
    story: "奥托不急着在纸上决定屋顶长什么样。他让链条下垂、薄膜绷紧、肥皂泡自动形成最小曲面，再把自然出现的受力关系转译成可建结构。实验与合作才是方法，照着轻盈曲线描一遍只剩姿态",
    creditNote: "慕尼黑奥运屋顶等项目必须注明 Günter Behnisch、工程团队与多方合作。",
    portrait: {
      src: "/images/architects-v7-illustrated/frei-otto-illustrated-v1.webp",
      alt: "弗莱·奥托低多边形风格化肖像，完整头肩与轻型张拉结构背景",
      source: { label: "Wikimedia Commons · OttoFrei", url: "https://commons.wikimedia.org/wiki/File:OttoFrei.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "The Pritzker Architecture Prize · Frei Otto", url: "https://www.pritzkerprize.com/laureates/2015" },
      { label: "Frei Otto Archive · saai", url: "https://www.saai.kit.edu/english/otto.php" },
    ],
  },
  {
    id: "ARCH-KERE",
    name: "弗朗西斯·凯雷",
    originalName: "Francis Kéré",
    lifespan: "1965—",
    region: "布基纳法索出生，主要在德国与国际工作",
    school: "地域现代主义 / 社区建造",
    summary: "他把气候、材料、教育和共同劳动组织成一件事，让有限资源中的屋顶成为真正的公共基础设施",
    storyTitle: "一片屋顶，把全村叫来",
    story: "Gando 小学最关键的动作是一套双层屋顶：较重的天花吸收热量，上方轻质金属屋顶遮阳，两者之间持续通风。当地社区参与材料制作和施工，学校因此既是建筑，也是长期积累技术与组织能力的过程",
    creditNote: "内容需呈现社区劳动、当地工匠、工程团队和 Kéré Architecture 的共同作者性。",
    portrait: {
      src: "/images/architects-v7-illustrated/francis-kere-illustrated-v1.webp",
      alt: "弗朗西斯·凯雷低多边形风格化肖像，完整头肩与双层屋顶背景",
      source: { label: "Wikimedia Commons · Francis Kere, 2019", url: "https://commons.wikimedia.org/wiki/File:Francis_Kere,_2019_(cropped).jpg", credit: "Astrid Eckert / TU München", status: "prototype-source-noted" },
    },
    sources: [
      { label: "The Pritzker Architecture Prize · Francis Kéré", url: "https://www.pritzkerprize.com/laureates/diebedo-francis-kere" },
      { label: "Kéré Architecture · Projects", url: "https://www.kerearchitecture.com/work" },
    ],
  },
  {
    id: "ARCH-YU",
    name: "俞孔坚 × 土人设计",
    originalName: "Kongjian Yu × Turenscape",
    lifespan: "1963—2025",
    region: "中国",
    school: "景观都市主义 / 生态基础设施",
    summary: "他和土人设计把洪水、湿地与公共生活放进同一套城市系统，以可淹没景观和海绵城市方法恢复自然循环",
    storyTitle: "最会劝城市和洪水交朋友的人",
    story: "俞孔坚长期主张把洪水视为可以被管理和利用的自然过程。永宁江、后滩与群力等项目让湿地、土壤和洪泛重新工作，同时保留公众可以进入的路径。他于 2025 年去世，方法与实践由团队、学生和土人设计继续推进",
    creditNote: "正式页面使用过去时，准确注明其 2025 年去世，并避免把大型团队项目改写成个人独作。",
    portrait: {
      src: "/images/architects-v7-illustrated/kongjian-yu-illustrated-v1.webp",
      alt: "俞孔坚低多边形风格化肖像，完整头肩与湿地水网背景",
      source: { label: "Wikimedia Commons · Yu Kongjian 2024", url: "https://commons.wikimedia.org/wiki/File:Yu_Kongjian_2024.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Turenscape · Kongjian Yu", url: "https://www.turenscape.com/en/about/index.html" },
      { label: "Harvard GSD · In Memoriam Kongjian Yu", url: "https://www.gsd.harvard.edu/2025/09/in-memoriam-kongjian-yu/" },
    ],
  },
  {
    id: "ARCH-KAHN",
    name: "路易斯·康",
    originalName: "Louis I. Kahn",
    lifespan: "1901—1974",
    region: "爱沙尼亚出生，主要在美国工作",
    school: "现代纪念性 / 原型空间",
    summary: "他用最基本的几何、厚墙和自然光赋予现代公共建筑一种像遗迹一样漫长的时间感",
    storyTitle: "让现代建筑提前拥有遗迹感",
    story: "康把空间区分为被服务空间与服务空间，让楼梯、设备和结构不再偷偷挤在剩余角落。索尔克、金贝尔与孟加拉国议会都用重复原型和精确自然光建立秩序，重量因此不只是表情，也承担公共制度和人的停留",
    creditNote: "项目叙事需注明事务所、工程师、景观与当地合作团队。",
    portrait: {
      src: "/images/architects-v7-illustrated/louis-kahn-illustrated-v1.webp",
      alt: "路易斯·康低多边形风格化肖像，完整头肩与圆形开口背景",
      source: { label: "Wikimedia Commons · LouisKahn", url: "https://commons.wikimedia.org/wiki/File:LouisKahn.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "The Louis I. Kahn Collection · University of Pennsylvania", url: "https://www.design.upenn.edu/architectural-archives/collections/louis-i-kahn-collection" },
      { label: "Kimbell Art Museum · Architecture", url: "https://kimbellart.org/art-architecture/architecture" },
    ],
  },
  {
    id: "ARCH-VENTURI-SCOTT-BROWN",
    name: "文丘里 × 斯科特·布朗",
    originalName: "Robert Venturi × Denise Scott Brown / VSBA",
    lifespan: "1925—2018 / 1931—",
    region: "美国",
    school: "后现代主义 / 建筑符号学",
    summary: "他们把普通街道、历史符号与大众传播带回建筑讨论，用幽默和复杂性挑战单一的现代主义纯度",
    storyTitle: "严肃建筑，也可以塞梗",
    story: "从《向拉斯维加斯学习》到事务所实践，两人把广告牌、汽车景观和普通建筑视为值得研究的公共语言。Scott Brown 长期面对共同作者身份被忽视的问题，因此这里不把理论与实践缩成单一男性建筑师故事",
    creditNote: "早期 Vanna Venturi House 与后续 VSBA 合作项目的署名必须分别说明。",
    portrait: {
      src: "/images/architects-v7-illustrated/venturi-scott-brown-illustrated-v1.webp",
      alt: "丹尼斯·斯科特·布朗与罗伯特·文丘里低多边形双人肖像，两人完整并列入镜",
      source: { label: "Wikimedia Commons · Denise Scott Brown", url: "https://commons.wikimedia.org/wiki/File:Denise_Scott_Brown.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "VSBA · About", url: "https://venturiscottbrown.org/about/" },
      { label: "The Pritzker Architecture Prize · Robert Venturi", url: "https://www.pritzkerprize.com/laureates/1991" },
    ],
  },
  {
    id: "ARCH-SANAA",
    name: "妹岛和世 × 西泽立卫",
    originalName: "Kazuyo Sejima × Ryue Nishizawa / SANAA",
    lifespan: "1956— / 1966—",
    region: "日本",
    school: "极简主义 / 非中心空间",
    summary: "他们用极薄边界、多入口和连续空间削弱中心与等级，让公共活动在精密组织中显得轻松",
    storyTitle: "最会让墙像没来上班的组合",
    story: "SANAA 的轻盈并不等于简单。金泽美术馆的圆形外轮廓、多入口与分散展厅，让参观者不用服从唯一正门和中心轴线；每一片薄墙背后，都有对距离、视线、声学和流线的精密控制",
    creditNote: "SANAA 内容必须同时呈现 Kazuyo Sejima 与 Ryue Nishizawa，并按具体项目核对合作者。",
    portrait: {
      src: "/images/architects-v7-illustrated/sanaa-illustrated-v1.webp",
      alt: "妹岛和世与西泽立卫低多边形双人肖像，两人完整并列入镜",
      source: { label: "Wikimedia Commons · Kazuyo Sejima", url: "https://commons.wikimedia.org/wiki/File:Canopy_Gathering_Space_(Kazuyo_Sejima)_(15137242547)_cropped.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "The Pritzker Architecture Prize · SANAA", url: "https://www.pritzkerprize.com/laureates/2010" },
      { label: "SANAA · Projects", url: "https://www.sanaa.co.jp/works/" },
    ],
  },
  {
    id: "ARCH-LACATON-VASSAL",
    name: "拉卡通 × 瓦萨尔",
    originalName: "Anne Lacaton × Jean-Philippe Vassal",
    lifespan: "1955— / 1954—",
    region: "法国",
    school: "改造伦理 / 社会住宅",
    summary: "他们以保留、少搬迁和空间加法改善存量建筑，把预算优先变成住户可以真正使用的自由面积",
    storyTitle: "最舍不得拆楼的建筑师组合",
    story: "他们常从一句简单判断开始：仍然能工作的建筑为什么要拆。Tour Bois-le-Prêtre 与 Grand Parc Bordeaux 用外扩结构、冬季花园和阳台提升住房面积，并尽量让居民继续住在原处。保留在这里是一套安全、经济、权利与生活质量共同参与的判断",
    creditNote: "住宅改造项目需注明 Frédéric Druot、Christophe Hutin 与具体合作团队。",
    portrait: {
      src: "/images/architects-v7-illustrated/lacaton-vassal-illustrated-v1.webp",
      alt: "安妮·拉卡通与让-菲利普·瓦萨尔低多边形双人肖像，两人完整并列入镜",
      source: { label: "Wikimedia Commons · Lacaton & Vassal Lecture", url: "https://commons.wikimedia.org/wiki/File:Lacaton_%26_Vassal_Lecture_at_Columbia_GSAPP.jpg", credit: "GSAPPstudent", status: "prototype-source-noted" },
    },
    sources: [
      { label: "The Pritzker Architecture Prize · Lacaton & Vassal", url: "https://www.pritzkerprize.com/laureates/anne-lacaton-and-jean-philippe-vassal" },
      { label: "Lacaton & Vassal · Projects", url: "https://www.lacatonvassal.com/index.php?idp=1" },
    ],
  },
  {
    id: "ARCH-OMA",
    name: "雷姆·库哈斯 × OMA",
    originalName: "Rem Koolhaas × Office for Metropolitan Architecture",
    lifespan: "1944— / 1975—",
    region: "荷兰 / 国际实践",
    school: "都市主义 / 程序混合",
    summary: "OMA 用剖面、研究与功能碰撞接住城市现实，让建筑成为可以容纳矛盾的内部城市",
    storyTitle: "最会把冲突写进剖面图的事务所",
    story: "西雅图中央图书馆把稳定功能压成平台，再以连续公共路线连接；Casa da Música 和 CCTV 也用不规则体量与环形组织制造新的相遇。OMA 是跨代际的大型合作组织，作品必须按项目呈现合伙人与团队",
    creditNote: "不可只以 Rem Koolhaas 个人天才叙事替代 OMA 合伙人、项目负责人、工程师和团队。",
    portrait: {
      src: "/images/architects-v7-illustrated/rem-koolhaas-illustrated-v1.webp",
      alt: "雷姆·库哈斯低多边形风格化肖像，完整头肩与叠合剖面背景",
      source: { label: "Wikimedia Commons · Rem Koolhaas 2013", url: "https://commons.wikimedia.org/wiki/File:Rem_Koolhaas_2013.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "OMA · About", url: "https://www.oma.com/about" },
      { label: "OMA · Projects", url: "https://www.oma.com/projects" },
    ],
  },
] as const;

export const ARCHITECT_BY_ID = Object.fromEntries(
  ARCHITECTS.map((architect) => [architect.id, architect]),
) as Record<string, Architect>;
