import type { Architect } from "./schema";

export const ARCHITECTS: readonly Architect[] = [
  {
    id: "ARCH-MIES",
    name: "密斯·凡·德·罗",
    originalName: "Ludwig Mies van der Rohe",
    lifespan: "1886—1969",
    region: "德国出生，后在美国工作",
    school: "现代主义 / 国际主义",
    summary: "他把结构、比例与材料压缩成极少的动作：柱子退开，墙体游走，石材与玻璃承担全部戏剧。",
    storyTitle: "被拆掉的经典，以及不能被删掉的合作者",
    story: "1929 年巴塞罗那德国馆在博览会结束后被拆除，却在建筑史中持续放大，最终于 1986 年在原址重建。展馆与 Barcelona Chair 的设计都应同时看到 Lilly Reich 的合作贡献；这个结果不把现代主义重新讲成单一男性天才神话。",
    creditNote: "巴塞罗那馆与家具须注明 Lilly Reich；西格拉姆大厦注明 Philip Johnson 等合作。",
    portrait: {
      src: "/images/architects-v2/mies.webp",
      alt: "密斯·凡·德·罗风格化肖像：白发、深色西装，坐在巴塞罗那馆抽象背景前",
      source: { label: "Wikimedia Commons · Ludwig Mies van der Rohe", url: "https://commons.wikimedia.org/wiki/File:Ludwig_Mies_van_der_Rohe_in_Arts_%26_Architecture,_June_1960_issue.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Fundació Mies van der Rohe · The Pavilion", url: "https://miesbcn.com/the-pavilion/" },
      { label: "MoMA · Ludwig Mies van der Rohe", url: "https://www.moma.org/artists/7166" },
    ],
  },
  {
    id: "ARCH-WRIGHT",
    name: "弗兰克·劳埃德·赖特",
    originalName: "Frank Lloyd Wright",
    lifespan: "1867—1959",
    region: "美国",
    school: "有机建筑 / 草原学派",
    summary: "他希望建筑不是摆在风景前面，而是把地形、材料、家具和人的生活组织成一个整体。",
    storyTitle: "他没有把瀑布放在窗外",
    story: "流水别墅最容易被记住的不是一张森林照片，而是一个激进决定：住宅的混凝土平台直接从岩石与水流上方伸出。住户不是远远观看瀑布，而是一直听见它、走在它上面。",
    creditNote: "作品说明应区分 Wright 个人设计、Taliesin Fellowship 与后续保存团队。",
    portrait: {
      src: "/images/architects-v2/wright.webp",
      alt: "弗兰克·劳埃德·赖特风格化肖像：白发、深色西装，一手托住太阳穴，背后是抽象流水别墅",
      source: { label: "Frank Lloyd Wright Foundation", url: "https://franklloydwright.org/frank-lloyd-wright/", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Frank Lloyd Wright Foundation · Fallingwater", url: "https://franklloydwright.org/site/fallingwater/" },
      { label: "Frank Lloyd Wright Foundation · Robie House", url: "https://franklloydwright.org/site/robie-house/" },
    ],
  },
  {
    id: "ARCH-CORBU",
    name: "勒·柯布西耶",
    originalName: "Le Corbusier / Charles-Édouard Jeanneret-Gris",
    lifespan: "1887—1965",
    region: "瑞士出生，主要在法国工作",
    school: "现代主义 / 粗野主义源流",
    summary: "他用住宅、模数与城市系统同时思考个体和集体；作品既有强烈秩序，也留下粗粝材料与巨大争议。",
    storyTitle: "一栋楼里塞进一座城市",
    story: "马赛公寓把复式住宅、内部商业街、托儿与屋顶设施叠在同一体量中，被构想为一座垂直城市。它不是孤身完成的英雄作品：André Wogenscky 领导的工作室与 ATBAT 团队都参与了实现。",
    creditNote: "马赛公寓注明 Atelier Le Corbusier、André Wogenscky 与 ATBAT；昌迪加尔注明项目团队与当地合作者。",
    portrait: {
      src: "/images/architects-v2/le-corbusier.webp",
      alt: "勒·柯布西耶风格化肖像：光头、黑色圆框眼镜与深色领结，背后是抽象马赛公寓",
      source: { label: "Fondation Le Corbusier · 1939–1946", url: "https://www.fondationlecorbusier.fr/en/biography/1939-1946/", credit: "Portrait © Bodé / Fondation Le Corbusier", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Fondation Le Corbusier · Unité d'Habitation", url: "https://www.fondationlecorbusier.fr/en/work-architecture/achievements-unite-dhabitation-marseille-france-1945-1952/" },
      { label: "Fondation Le Corbusier · La Tourette", url: "https://www.fondationlecorbusier.fr/oeuvre-architecture/realisations-couvent-sainte-marie-de-la-tourette-eveux-sur-larbresle-france-1953-1960/" },
    ],
  },
  {
    id: "ARCH-ANDO",
    name: "安藤忠雄",
    originalName: "Tadao Ando",
    lifespan: "1941—",
    region: "日本",
    school: "诗意极简 / 清水混凝土",
    summary: "他的建筑常用极少材料和绕行路径，把光、风、水与身体感受放大到近乎宗教性的程度。",
    storyTitle: "先绕路，再看到光",
    story: "安藤的空间经常拒绝最短路线：人要绕过墙、向下走或穿过水面，才抵达核心。光之教堂把十字形开口切进混凝土墙，最简单的几何因此成为最强烈的感受。",
    portrait: {
      src: "/images/architects-v2/ando.webp",
      alt: "安藤忠雄风格化肖像：黑色直发、深色外套与高白领，背后是光之教堂的十字形开口",
      source: { label: "Wikimedia Commons · Tadao Ando", url: "https://commons.wikimedia.org/wiki/File:Tadao_Ando_2004_(4x5_cropped).jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "The Pritzker Architecture Prize · Tadao Ando", url: "https://www.pritzkerprize.com/laureates/1995" },
      { label: "Benesse Art Site Naoshima · Chichu Art Museum", url: "https://benesse-artsite.jp/en/art/chichu.html" },
    ],
  },
  {
    id: "ARCH-FOSTER",
    name: "诺曼·福斯特",
    originalName: "Norman Foster / Foster + Partners",
    lifespan: "1935—",
    region: "英国及全球",
    school: "高技派",
    summary: "他把结构、环境系统、交通与公共空间当成同一台大型机器来设计，同时不断追求更轻、更透明的城市基础设施。",
    storyTitle: "系统理性也要问风水",
    story: "香港汇丰总行几乎所有部件都为项目专门设计并在外地制造后运到香港装配。项目还纳入了风水顾问：真正的系统思维不是只信技术，而是知道技术必须进入具体城市文化。",
    creditNote: "所有作品使用 Foster + Partners 团队署名，不简化成 Foster 独立完成。",
    portrait: {
      src: "/images/architects-v2/foster.webp",
      alt: "诺曼·福斯特风格化肖像：银灰短发、浅蓝衬衫，双臂交叠站在汇丰总行抽象桁架前",
      source: { label: "The Pritzker Architecture Prize · Norman Foster", url: "https://www.pritzkerprize.com/laureates/1999", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Foster + Partners · Hongkong and Shanghai Bank Headquarters", url: "https://www.fosterandpartners.com/projects/hongkong-and-shanghai-bank-headquarters/" },
      { label: "HSBC · Back to the future", url: "https://www.hsbc.com/news-and-views/news/hsbc-news-archive/back-to-the-future" },
    ],
  },
  {
    id: "ARCH-ZAHA",
    name: "扎哈·哈迪德",
    originalName: "Zaha Hadid / Zaha Hadid Architects",
    lifespan: "1950—2016",
    region: "伊拉克出生，英国及全球",
    school: "解构主义 / 新未来主义",
    summary: "她把绘画中的碎裂透视、速度与连续地形推进到真实建造，让空间看起来像正在发生而不是已经完成。",
    storyTitle: "纸上的高速城市终于落地",
    story: "她早期许多激进方案主要通过竞赛图与绘画被认识，长期被称作难以建成的“纸上建筑师”。随着数字设计、工程与制造能力变化，那些倾斜、流动与连续的空间才逐渐成为城市中的真实建筑。",
    creditNote: "2016 年后的作品与大型项目均使用 Zaha Hadid Architects 团队署名。",
    portrait: {
      src: "/images/architects-v2/zaha.webp",
      alt: "扎哈·哈迪德风格化肖像：深色长发与黑色外套，背后是海达尔·阿利耶夫中心的抽象曲线",
      source: { label: "Wikimedia Commons · Zaha Hadid", url: "https://commons.wikimedia.org/wiki/File:Zaha_Hadid_in_Heydar_Aliyev_Cultural_center_in_Baku_nov_2013.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Zaha Hadid Architects · Architecture", url: "https://www.zaha-hadid.com/architecture/" },
      { label: "The Pritzker Architecture Prize · Zaha Hadid", url: "https://www.pritzkerprize.com/laureates/2004" },
    ],
  },
  {
    id: "ARCH-GAUDI",
    name: "安东尼·高迪",
    originalName: "Antoni Gaudí",
    lifespan: "1852—1926",
    region: "加泰罗尼亚",
    school: "加泰罗尼亚现代主义 / 新艺术",
    summary: "他把结构实验、自然几何、宗教叙事和工匠技术揉成总体艺术；装饰不是贴上去，而是从建造逻辑里长出。",
    storyTitle: "失败住宅区变成了城市乐园",
    story: "Park Güell 原本是受英国花园城市启发的高端住宅开发，但销售困难，最终只建成两栋住宅。失败的地产计划后来变成公共公园，曲线长椅、碎瓷拼贴与基础设施反而获得了更长的城市生命。",
    creditNote: "圣家堂持续由多代建筑师、工匠和工程团队推进，不能写成高迪独自完成。",
    portrait: {
      src: "/images/architects-v2/gaudi.webp",
      alt: "安东尼·高迪风格化肖像：侧分深发、浓密胡须与深色历史西装，背后是巴特罗之家抽象立面",
      source: { label: "Wikimedia Commons · Antoni Gaudí", url: "https://commons.wikimedia.org/wiki/File:Antoni_Gaudi_1878.jpg", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Casa Batlló · Gaudí works", url: "https://www.casabatllo.es/en/antoni-gaudi/works/" },
      { label: "Casa Batlló · Park Güell", url: "https://www.casabatllo.es/en/antoni-gaudi/park-guell/" },
    ],
  },
  {
    id: "ARCH-WANG-LU",
    name: "王澍 × 陆文宇",
    originalName: "Wang Shu × Lu Wenyu / Amateur Architecture Studio",
    lifespan: "1963— / 1967—",
    region: "中国",
    school: "批判地域主义 / 材料再生",
    summary: "他们用回收砖瓦、地方工法和当代空间重新连接快速城市化中被切断的材料记忆。",
    storyTitle: "为什么工作室偏要叫“业余”",
    story: "“业余建筑工作室”这个名字并非不专业，而是对只剩生产效率的职业系统保持距离。宁波历史博物馆的旧砖瓦来自周边拆迁地区，材料以新的墙体重新出现，也把消失村落的一部分时间带回城市。",
    creditNote: "人物与项目内容必须同时呈现陆文宇、王澍、业余建筑工作室和建造团队，避免单一获奖者叙事。",
    portrait: {
      src: "/images/architects-v2/wang-lu.webp",
      alt: "王澍与陆文宇的双人风格化肖像：两人等距并肩站立，背后是宁波历史博物馆的抽象墙面",
      source: { label: "Wallpaper* · Wang Shu and Lu Wenyu", url: "https://www.wallpaper.com/architecture/wang-shu-and-lu-wenyu-curators-2027-venice-architecture-biennale", credit: "La Biennale di Venezia / ASAC / Matteo Losurdo", status: "prototype-source-noted" },
    },
    sources: [
      { label: "Pritzker Prize · Wang Shu essay", url: "https://www.pritzkerprize.com/sites/default/files/file_fields/field_files_inline/2013_essay.pdf" },
      { label: "Pritzker Prize · The Infinite Spontaneity of Tradition", url: "https://www.pritzkerprize.com/sites/default/files/inline-files/2012_Essay_0.pdf" },
    ],
  },
] as const;

export const ARCHITECT_BY_ID = Object.fromEntries(
  ARCHITECTS.map((architect) => [architect.id, architect]),
) as Record<string, Architect>;
