import type { Question } from "./schema";

export const QUESTIONS: readonly Question[] = [
  {
    id: "Q01",
    order: 1,
    kind: "projective",
    eyebrow: "空间本能 · 01",
    prompt: "推开一扇陌生的门，你希望空间先做什么？",
    options: [
      {
        id: "A",
        label: "把声音轻轻压低",
        evidence: "进入陌生空间时，你先寻找能让感官安静下来的边界",
        weights: { SOCIAL: -0.9, EXPRESS: -0.65 },
      },
      {
        id: "B",
        label: "把去向一眼讲清",
        evidence: "你希望空间先把路线说明白，再谈情绪",
        weights: { ORDER: 0.9, MAKING: -0.65 },
      },
      {
        id: "C",
        label: "让视线一直跑到远处",
        evidence: "你容易被没有视觉阻挡的空间吸引",
        weights: { SOCIAL: 0.9, EXPRESS: 0.65 },
      },
    ],
  },
  {
    id: "Q02",
    order: 2,
    kind: "projective",
    eyebrow: "空间本能 · 02",
    prompt: "一间空房只允许留下一面墙，你选哪一面？",
    options: [
      {
        id: "A",
        label: "干净到看不出年代的墙",
        evidence: "你欣赏脱离具体年代、只留下比例和表面的空间",
        weights: { CONTEXT: -0.85, TIME: -0.65 },
      },
      {
        id: "B",
        label: "让光每天换位置的墙",
        evidence: "你愿意让一天中的光线替空间持续改写表情",
        weights: { EXPRESS: -0.75, TIME: 0.55 },
      },
      {
        id: "C",
        label: "保留修补痕迹的旧墙",
        evidence: "你不会急着抹掉材料已经经历过的时间",
        weights: { CONTEXT: 0.85, TIME: 0.75 },
      },
    ],
  },
  {
    id: "Q03",
    order: 3,
    kind: "projective",
    eyebrow: "空间本能 · 03",
    prompt: "雨要来了，你会先走进哪一处？",
    options: [
      {
        id: "A",
        label: "能独自听雨的深廊",
        evidence: "你偏爱有厚度的边界，让天气靠近却不必打扰你",
        weights: { SOCIAL: -0.9, EXPRESS: -0.55 },
      },
      {
        id: "B",
        label: "三五个人刚好站下的屋檐",
        evidence: "你喜欢既能相遇又不过度暴露的中间地带",
        weights: { SOCIAL: 0.2, CONTEXT: 0.75 },
      },
      {
        id: "C",
        label: "所有人都能穿过的大厅",
        evidence: "你会把空间是否欢迎更多人放在优先位置",
        weights: { SOCIAL: 0.9, EXPRESS: 0.45 },
      },
    ],
  },
  {
    id: "Q04",
    order: 4,
    kind: "projective",
    eyebrow: "空间本能 · 04",
    prompt: "梦里的城市只剩一套路，你会留下哪一种？",
    options: [
      {
        id: "A",
        label: "一条对准远处的街道",
        evidence: "你相信清楚的方向本身就能给人安全感",
        weights: { ORDER: 0.9, GEOMETRY: 0.7 },
      },
      {
        id: "B",
        label: "几条彼此接上的小路",
        evidence: "你愿意让路线顺着现场生长，并保留偶遇的可能",
        weights: { ORDER: -0.25, CONTEXT: 0.85 },
      },
      {
        id: "C",
        label: "一条绕开所有边界的自由路径",
        evidence: "当规则阻挡体验时，你更愿意先试一条没有先例的路",
        weights: { ORDER: -0.9, RISK: 0.75 },
      },
    ],
  },
  {
    id: "Q05",
    order: 5,
    kind: "projective",
    eyebrow: "空间本能 · 05",
    prompt: "城市忽然静音，你希望最后还听见什么？",
    options: [
      {
        id: "A",
        label: "脚步落在空房里的回声",
        evidence: "你对空白和细小变化很敏感，少量声音已经足够",
        weights: { SOCIAL: -0.8, EXPRESS: -0.7 },
      },
      {
        id: "B",
        label: "人群从庭院传来的低声",
        evidence: "你喜欢可以感到他人存在、又不过分拥挤的距离",
        weights: { SOCIAL: 0.75, CONTEXT: 0.55 },
      },
      {
        id: "C",
        label: "电梯、风机和轨道的合奏",
        evidence: "你会注意维持城市运行的系统，并把它们听成一种秩序",
        weights: { MAKING: -0.85, TIME: -0.7 },
      },
    ],
  },
  {
    id: "Q06",
    order: 6,
    kind: "projective",
    eyebrow: "空间本能 · 06",
    prompt: "捡到一块来历不明的材料，你先做什么？",
    options: [
      {
        id: "A",
        label: "量好尺寸，接进现有系统",
        evidence: "面对陌生材料时，你先确认它如何进入一套可理解的结构",
        weights: { MAKING: -0.9, ORDER: 0.7 },
      },
      {
        id: "B",
        label: "直接动手，看它会变成什么",
        evidence: "你更相信试作中的反馈，而不是一开始就把结果锁死",
        weights: { MAKING: 0.9, RISK: 0.7 },
      },
      {
        id: "C",
        label: "先找它以前属于哪里",
        evidence: "在决定材料的新用途前，你会先追问它来自哪里",
        weights: { CONTEXT: 0.85, TIME: 0.8 },
      },
    ],
  },
  {
    id: "Q07",
    order: 7,
    kind: "personality",
    eyebrow: "空间价值 · 07",
    prompt: "一栋好建筑最不应该失去什么？",
    options: [
      {
        id: "A",
        label: "一眼能读懂的秩序",
        evidence: "你认为复杂可以存在，但空间必须给出可读的骨架",
        weights: { ORDER: 0.9, GEOMETRY: 0.6 },
      },
      {
        id: "B",
        label: "与环境相处的方式",
        evidence: "你会先判断建筑有没有听见风景、气候和附近生活",
        weights: { CONTEXT: 0.9, GEOMETRY: -0.55 },
      },
      {
        id: "C",
        label: "让人忘不掉的个性",
        evidence: "你愿意为鲜明表达承担一点不确定性",
        weights: { EXPRESS: 0.9, RISK: 0.55 },
      },
    ],
  },
  {
    id: "Q08",
    order: 8,
    kind: "personality",
    eyebrow: "空间价值 · 08",
    prompt: "预算只够保住一种东西，你留下什么？",
    options: [
      {
        id: "A",
        label: "结构和比例",
        evidence: "你相信骨架与尺度准确，空间就不会轻易失去力量",
        weights: { ORDER: 0.8, MAKING: -0.7 },
      },
      {
        id: "B",
        label: "人们共同使用的地方",
        evidence: "你更在意建筑能不能容纳真实的共同生活",
        weights: { SOCIAL: 0.9, ORDER: 0.25 },
      },
      {
        id: "C",
        label: "材料和手工留下的触感",
        evidence: "你愿意把有限资源留给手能摸到的真实细节",
        weights: { MAKING: 0.9, TIME: 0.55 },
      },
    ],
  },
  {
    id: "Q09",
    order: 9,
    kind: "personality",
    eyebrow: "空间价值 · 09",
    prompt: "哪种缺点，你反而比较愿意原谅？",
    options: [
      {
        id: "A",
        label: "太克制，但足够准确",
        evidence: "只要比例和判断准确，你不介意空间少说一点",
        weights: { EXPRESS: -0.85, ORDER: 0.8 },
      },
      {
        id: "B",
        label: "有些混乱，但充满生命",
        evidence: "你愿意用一点不整齐，换取空间继续生长的活力",
        weights: { ORDER: -0.75, CONTEXT: 0.65 },
      },
      {
        id: "C",
        label: "不够实用，但让人忘不掉",
        evidence: "如果体验足够强烈，你愿意暂时放下效率标准",
        weights: { EXPRESS: 0.9, RISK: 0.6 },
      },
    ],
  },
  {
    id: "Q10",
    order: 10,
    kind: "personality",
    eyebrow: "空间价值 · 10",
    prompt: "面对一栋旧建筑，你最想先保住什么？",
    options: [
      {
        id: "A",
        label: "仍然有效的结构秩序",
        evidence: "你会先辨认旧建筑中仍然准确、还能继续工作的骨架",
        weights: { ORDER: 0.85, TIME: -0.25 },
      },
      {
        id: "B",
        label: "材料留下的时间痕迹",
        evidence: "你把磨损和修补看作建筑已经活过的证据",
        weights: { TIME: 0.9, MAKING: 0.7 },
      },
      {
        id: "C",
        label: "人们继续使用它的方式",
        evidence: "你认为更新首先要让原有生活有机会接着发生",
        weights: { SOCIAL: 0.9, CONTEXT: 0.7 },
      },
    ],
  },
  {
    id: "Q11",
    order: 11,
    kind: "personality",
    eyebrow: "空间价值 · 11",
    prompt: "公共空间首先应该让人怎样？",
    options: [
      {
        id: "A",
        label: "马上知道应该往哪里走",
        evidence: "你把清晰导航看作公共空间对陌生人的基本尊重",
        weights: { ORDER: 0.85, MAKING: -0.55 },
      },
      {
        id: "B",
        label: "找到愿意停下来的位置",
        evidence: "你会用能否舒服停留，判断一个地方是否真正成立",
        weights: { CONTEXT: 0.85, SOCIAL: 0.2 },
      },
      {
        id: "C",
        label: "可以改变它原来的用法",
        evidence: "你喜欢给使用者留下改写空间规则的余地",
        weights: { RISK: 0.8, ORDER: -0.65 },
      },
    ],
  },
  {
    id: "Q12",
    order: 12,
    kind: "personality",
    eyebrow: "空间价值 · 12",
    prompt: "建筑完成以后，哪种状态最理想？",
    options: [
      {
        id: "A",
        label: "很多年后仍保持最初精度",
        evidence: "你欣赏能够抵抗时间干扰、长期维持清楚边界的设计",
        weights: { ORDER: 0.9, TIME: -0.55 },
      },
      {
        id: "B",
        label: "被天气和使用慢慢改变",
        evidence: "你愿意让天气和日常使用继续参与建筑的完成",
        weights: { TIME: 0.9, CONTEXT: 0.65 },
      },
      {
        id: "C",
        label: "能够不断拆换和升级",
        evidence: "你更信任可以维护和迭代的系统，而不是一次定型",
        weights: { MAKING: -0.9, ORDER: 0.55 },
      },
    ],
  },
  {
    id: "Q13",
    order: 13,
    kind: "aesthetic",
    eyebrow: "建筑直觉 · 13",
    prompt: "哪一种体量让你更想靠近？",
    options: [
      {
        id: "A",
        label: "沉稳落地、把人托住的体量",
        evidence: "你会靠近有重量、有边界、能稳稳承托公共生活的建筑",
        visual: "mass",
        weights: { GEOMETRY: 0.7, SOCIAL: 0.55 },
      },
      {
        id: "B",
        label: "正在加速、几乎不停下的曲面",
        evidence: "连续变化的轮廓比安静的盒子更容易抓住你的注意",
        visual: "flow",
        weights: { GEOMETRY: -0.85, EXPRESS: 0.85 },
      },
      {
        id: "C",
        label: "轻得像能随时升级的结构骨架",
        evidence: "你喜欢把结构和连接直接看见，并想象它下一步如何扩展",
        visual: "module",
        weights: { ORDER: 0.8, MAKING: -0.85 },
      },
    ],
  },
  {
    id: "Q14",
    order: 14,
    kind: "aesthetic",
    eyebrow: "建筑直觉 · 14",
    prompt: "哪个空间会让你忘记看时间？",
    options: [
      {
        id: "A",
        label: "暗处只有一道光，脚步也慢下来",
        evidence: "你会被光线很少、但每一道都准确的空间留住",
        visual: "light",
        weights: { EXPRESS: -0.9, SOCIAL: -0.7 },
      },
      {
        id: "B",
        label: "树、风和座位围成安静庭院",
        evidence: "你喜欢建筑退到周围，让树影和天气成为空间主角",
        visual: "courtyard",
        weights: { GEOMETRY: -0.8, CONTEXT: 0.8 },
      },
      {
        id: "C",
        label: "色彩和细节沿楼梯一路生长",
        evidence: "你愿意跟着颜色与细节移动，让空间不断给出新发现",
        visual: "ornament",
        weights: { EXPRESS: 0.9, MAKING: 0.65 },
      },
    ],
  },
  {
    id: "Q15",
    order: 15,
    kind: "aesthetic",
    eyebrow: "建筑直觉 · 15",
    prompt: "伸手摸墙，你更想碰到什么？",
    options: [
      {
        id: "A",
        label: "带着温度和旧痕的砖",
        evidence: "材料已经经历过的天气与触摸，会增加你对空间的信任",
        visual: "earth",
        weights: { TIME: 0.85, CONTEXT: 0.75 },
      },
      {
        id: "B",
        label: "粗粝厚实、留着模板纹的混凝土",
        evidence: "你喜欢材料不遮掩建造过程，重量和纹理都直接在场",
        visual: "concrete",
        weights: { GEOMETRY: 0.75, EXPRESS: 0.45 },
      },
      {
        id: "C",
        label: "冷而精准、接缝几乎消失的金属",
        evidence: "你会注意接缝和误差，并欣赏工业构件被控制到几乎无声",
        visual: "steel",
        weights: { ORDER: 0.85, MAKING: -0.85 },
      },
    ],
  },
  {
    id: "Q16",
    order: 16,
    kind: "aesthetic",
    eyebrow: "建筑直觉 · 16",
    prompt: "同一个房间，你会留下哪一种窗？",
    options: [
      {
        id: "A",
        label: "一条连续而守秩序的水平长窗",
        evidence: "你喜欢视线被一条清楚的水平线整理起来",
        visual: "ribbon",
        weights: { ORDER: 0.9, GEOMETRY: 0.7 },
      },
      {
        id: "B",
        label: "几扇只框住树梢和屋顶的小窗",
        evidence: "你更在意窗选择看什么，而不是把所有景色一次交出来",
        visual: "framed",
        weights: { CONTEXT: 0.9, EXPRESS: -0.3 },
      },
      {
        id: "C",
        label: "一整面让天气进入视线的巨窗",
        evidence: "你愿意让远景、光线和天气直接占据整个房间",
        visual: "giant",
        weights: { SOCIAL: 0.65, EXPRESS: 0.85 },
      },
    ],
  },
  {
    id: "Q17",
    order: 17,
    kind: "aesthetic",
    eyebrow: "建筑直觉 · 17",
    prompt: "同一块城市空地，你希望它先成为什么？",
    options: [
      {
        id: "A",
        label: "接起旧巷、院落和新生活的路径",
        evidence: "你更愿意从修补关系开始，让新建筑接住原来的生活",
        visual: "repair",
        weights: { CONTEXT: 0.9, TIME: 0.75 },
      },
      {
        id: "B",
        label: "从地面一路翻上屋顶的开放公园",
        evidence: "你喜欢地面与建筑彼此流动，让公共空间没有明确终点",
        visual: "landscape",
        weights: { GEOMETRY: -0.85, EXPRESS: 0.75 },
      },
      {
        id: "C",
        label: "可以加层、拆换和升级的公共骨架",
        evidence: "你希望公共建筑把变化能力直接留在结构里",
        visual: "module",
        weights: { ORDER: 0.8, MAKING: -0.85 },
      },
    ],
  },
  {
    id: "Q18",
    order: 18,
    kind: "aesthetic",
    eyebrow: "建筑直觉 · 18",
    prompt: "哪种不完美，你反而愿意保留？",
    options: [
      {
        id: "A",
        label: "网格里故意空出来的一格",
        evidence: "你喜欢规则先成立，再用一个克制的缺口让它呼吸",
        visual: "grid-gap",
        weights: { ORDER: 0.85, EXPRESS: -0.45 },
      },
      {
        id: "B",
        label: "材料慢慢开裂、长苔和变色",
        evidence: "你愿意把风化看成时间参与设计，而不是单纯的损耗",
        visual: "weather",
        weights: { TIME: 0.9, MAKING: 0.7 },
      },
      {
        id: "C",
        label: "一段现在还造不出来的悬空曲面",
        evidence: "即使技术暂时追不上，你也愿意为新的空间可能留位置",
        visual: "impossible",
        weights: { RISK: 0.9, TIME: -0.7 },
      },
    ],
  },
] as const;

if (QUESTIONS.length !== 18) {
  throw new Error("The product contract requires exactly 18 questions");
}
